server:
  port: 9991
spring:
  cloud:
    config:
      server:
        default-application-name: config-server
        git:
          uri: git@gitee.com:aarontester/cloudbasic-config.git
          basedir: E:\Gitee\cloudbasic-config
  application:
    name: config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/