server:
  port: 80
spring:
  application:
    name: cloudbasic-consumer
logging:
  config: classpath:logback.xml
  level:
    cn.jay.repository: trace

eureka:
  instance:
    prefer-ip-address: true
    instance-id: cloudbasic-consumer-feign-80
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
